on: push
name: Publish to Github Pages      
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
      - uses: actions/checkout@v4
      # Download and run TailwindCSS
      - name: TailwindCSS Build
        run: |
             curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/download/v3.4.6/tailwindcss-linux-x64
             chmod +x tailwindcss-linux-x64
             mv tailwindcss-linux-x64 /usr/local/bin/tailwindcss
             tailwindcss -i src-styles/base.scss -o static/styles/main.css --minify
      - name: Zola Deploy
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: .
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
